### ISSUE TITLE
Guide to Project Workflow

### ISSUE THREAD

**Issue by SHUNLU-1** [ankile/robust-rearrangement#25]
Thank you very much for your excellent work, Could you please add the Guide to Project Workflow, Can I add a simple workflow？

**Comment by ankile** [comment]
Hi, thanks for reaching out! I'm sorry for not seeing your message and getting back to you sooner. We're currently working on making the code easier to run for anyone, so there should be updates regarding this on the main branch shortly and I will let you know once we have updates.

I hope this makes sense and that the code being open can still be of help despite not being straightforward to run out of the box yet.

Best, Lars

**Comment by ankile** [comment]
Hi, again!

Sorry for not getting back to you sooner—I was sure I had reached back out...

We're not fully there yet, but the dataset and code for training the BC policies are there—and the rest is on the way.

Best, Lars

**Comment by SHUNLU-1** [comment]
Thank you very much for your reply
