### ISSUE TITLE
h100 issue with isaacgym

### ISSUE THREAD

**Issue by edwardjjj** [ankile/robust-rearrangement#29]
Hi, Thank you for sharing your work!

I'm trying to run the script on an H100 GPU. It just gives a segfault after `+++ Using GPU PhysX`.
I also saw you posting on isaacgym github page. I'm wondering if you have found a solution to it?

**Comment by chenzixuan99** [comment]
Hi, I’m encountering the same segfault issue. Could you please share how you resolved it? 

Thank you so much!
